// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// OLS_cpp
arma::vec OLS_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _lavaSearch2_OLS_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(OLS_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// OLS2_cpp
arma::vec OLS2_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _lavaSearch2_OLS2_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(OLS2_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lavaSearch2_OLS_cpp", (DL_FUNC) &_lavaSearch2_OLS_cpp, 2},
    {"_lavaSearch2_OLS2_cpp", (DL_FUNC) &_lavaSearch2_OLS2_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lavaSearch2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
